languageCode = "en-En"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "BloxEe"
copyright = "&copy; 2023 BloxEe studios"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["games"]
  description = "A video game developement studio that specializes in creating high-quality games designed to deliver  a captivating and emotional gaming experience accross multiple platforms"

[author]
  name = "BloxEe Team"
  image = "img/lgo2.png"
  headline = "specteculerrr"
  bio = "A video game developement studio that specializes in creating high-quality games designed to deliver  a captivating and emotional gaming experience accross multiple platforms :dog:"
  links = [
    { x-twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
