# -- メインメニュー --
# メインメニューはページの上部にヘッダーとして表示されます。
# 受け入れ可能なパラメータはname、pageRef、page、url、title、weightです。
#
# 最も簡単なメニューの構成は次のとおりです：
#   name = このメニューリンクの表示名
#   pageRef = リンク先のページまたはセクションの識別子
#
# メニューはデフォルトでアルファベット順に並び替えられます。これは
# weight値を提供することでオーバーライドできます。メニューはその後
# weightが最も低いものから最も高いものまで順に並べ替えられます。

[[main]]
  name = "紹介"
  pageRef = "about"
  weight = 10

[[main]]
  name = "ゲーム"
  pageRef = "games"
  weight = 20

[[main]]
  name = "チーム"
  pageRef = "team"
  weight = 30

[[main]]
  name = "お問い合わせ"
  pageRef = "contact"
  weight = 40

[[main]]
  name = "GitHub"
  url = "https://github.com/Cprime50/BloxEe"
  weight = 50
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"
